packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - protobufjs
  - sharp
  - supabase
  - unrs-resolver
